// <auto-generated />
using System;
using EFDbServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDbServices.Migrations
{
    [DbContext(typeof(EFDataContext))]
    [Migration("20181205064914_core01")]
    partial class core01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFDbServices.RoleManagement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeleteBy");

                    b.Property<DateTime>("DeleteDateTime");

                    b.Property<int>("InsertBy");

                    b.Property<DateTime>("InsertDateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnName("RoleCode")
                        .HasMaxLength(50);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnName("RoleName")
                        .HasMaxLength(50);

                    b.Property<int>("UpdateBy");

                    b.Property<DateTime>("UpdateDateTime");

                    b.Property<int?>("UserManagementID");

                    b.HasKey("ID");

                    b.HasIndex("UserManagementID");

                    b.ToTable("RoleManagements");
                });

            modelBuilder.Entity("EFDbServices.UserManagement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeleteBy");

                    b.Property<DateTime>("DeleteDateTime");

                    b.Property<int>("InsertBy");

                    b.Property<DateTime>("InsertDateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdateBy");

                    b.Property<DateTime>("UpdateDateTime");

                    b.Property<string>("UserLoginCode")
                        .IsRequired()
                        .HasColumnName("UserLoginCode")
                        .HasMaxLength(20);

                    b.Property<string>("UserLoginPwd")
                        .IsRequired()
                        .HasColumnName("UserLoginPwd")
                        .HasMaxLength(40);

                    b.Property<string>("UserNmae")
                        .IsRequired()
                        .HasColumnName("UserNmae")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("UserManagements");
                });

            modelBuilder.Entity("EFDbServices.RoleManagement", b =>
                {
                    b.HasOne("EFDbServices.UserManagement")
                        .WithMany("RoleManagements")
                        .HasForeignKey("UserManagementID");
                });
#pragma warning restore 612, 618
        }
    }
}
